services:
  api-service:
    container_name: caldesk_api
    build:
      context: ./api
      dockerfile: Dockerfile.dev
    command: ["pnpm", "run", "dev"]
    env_file:
      - ./api/.env
    volumes:
      - ./api:/app
      - /app/node_modules
    ports:
      - "8080:8080" # HOST_PORT : CONTAINER_PORT
    networks:
      - caldesk_network
  db:
    container_name: caldesk-postgres
    image: postgres:16.6
    env_file:
      - ./api/.env
    ports:
      - 5432:5432
    volumes:
      - ./postgresql/data:/var/lib/postgresql/data
    networks:
      - caldesk_network

networks:
  caldesk_network:
    driver: bridge
